# Is it useful ?!

In [7]:
import os
import pandas as pd

DATA_DIR = "/nfs/scratch/pdb_dimers/KaHIP"

In [8]:
output = pd.read_csv(os.path.join(DATA_DIR, "output.txt"), header=None)
output.head()

   0
0  3
1  3
2  3
3  3
4  3

In [9]:
output["cluster_id"] = output.index.map(lambda x: x + 1)  # METIS uses 1-based indexing
output.head()

   0  cluster_id
0  3           1
1  3           2
2  3           3
3  3           4
4  3           5

In [11]:
# Plot the distribution of cluster sizes
cluster_sizes = output[0].value_counts().sort_index()
print(cluster_sizes)

0
0    799
1    799
2    798
3    796
4    798
5    799
6    798
7    798
8    799
9    799
Name: count, dtype: int64